# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: args.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='args.proto',
  package='difflearning',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nargs.proto\x12\x0c\x64ifflearning\"}\n\x0bInputParams\x12\x11\n\x05xTest\x18\x01 \x03(\x01\x42\x02\x10\x01\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0e\n\x06isDiff\x18\x03 \x01(\x08\x12\x12\n\x06xTrain\x18\x04 \x03(\x01\x42\x02\x10\x01\x12\x12\n\x06yTrain\x18\x05 \x03(\x01\x42\x02\x10\x01\x12\x15\n\tdydxTrain\x18\x06 \x03(\x01\x42\x02\x10\x01\x62\x06proto3'
)




_INPUTPARAMS = _descriptor.Descriptor(
  name='InputParams',
  full_name='difflearning.InputParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xTest', full_name='difflearning.InputParams.xTest', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='difflearning.InputParams.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isDiff', full_name='difflearning.InputParams.isDiff', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xTrain', full_name='difflearning.InputParams.xTrain', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yTrain', full_name='difflearning.InputParams.yTrain', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dydxTrain', full_name='difflearning.InputParams.dydxTrain', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['InputParams'] = _INPUTPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputParams = _reflection.GeneratedProtocolMessageType('InputParams', (_message.Message,), {
  'DESCRIPTOR' : _INPUTPARAMS,
  '__module__' : 'args_pb2'
  # @@protoc_insertion_point(class_scope:difflearning.InputParams)
  })
_sym_db.RegisterMessage(InputParams)


_INPUTPARAMS.fields_by_name['xTest']._options = None
_INPUTPARAMS.fields_by_name['xTrain']._options = None
_INPUTPARAMS.fields_by_name['yTrain']._options = None
_INPUTPARAMS.fields_by_name['dydxTrain']._options = None
# @@protoc_insertion_point(module_scope)
